"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import DailyKpiPanel from "./components/DailyKpiPanel";
import OrderFlowPanel from "./components/OrderFlowPanel";
import ReplayOperationsPanel from "./components/ReplayOperationsPanel";
import AlertOperationsPanel from "./components/AlertOperationsPanel";
import AlertPolicyPanel, { PolicyInput } from "./components/AlertPolicyPanel";
import type { AlertPolicy, AlertPolicyAudit, CustomerOrder, DailyDeliveryKpi, DeadLetterEvent, Delivery, DeliveryAlert, LedgerEntry, ReplayAudit, RouteSnapshot, WarehouseStock, WarehouseTask } from "./types";

const FleetMap=dynamic(()=>import("./components/FleetMap"),{ssr:false});
const API=process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";

export default function Home(){
 const [items,setItems]=useState<Delivery[]>([]); const [connected,setConnected]=useState(false); const [error,setError]=useState(""); const [selected,setSelected]=useState<string>();
 const [fleetScope,setFleetScope]=useState<"LIVE"|"ALL">("LIVE"); const [fleetQuery,setFleetQuery]=useState("");
 const [routes,setRoutes]=useState<RouteSnapshot[]>([]);
 const [alerts,setAlerts]=useState<DeliveryAlert[]>([]);
 const [alertBusy,setAlertBusy]=useState<string>();
 const [policies,setPolicies]=useState<AlertPolicy[]>([]); const [policyAudits,setPolicyAudits]=useState<AlertPolicyAudit[]>([]); const [policyBusy,setPolicyBusy]=useState(false);
 const [orders,setOrders]=useState<CustomerOrder[]>([]); const [orderBusy,setOrderBusy]=useState<string>();
 const [kpis,setKpis]=useState<DailyDeliveryKpi[]>([]);
 const [deadLetters,setDeadLetters]=useState<DeadLetterEvent[]>([]); const [replayAudits,setReplayAudits]=useState<ReplayAudit[]>([]); const [replayBusy,setReplayBusy]=useState<string>();
 const [stocks,setStocks]=useState<WarehouseStock[]>([]); const [tasks,setTasks]=useState<WarehouseTask[]>([]); const [ledger,setLedger]=useState<LedgerEntry[]>([]); const [warehouseBusy,setWarehouseBusy]=useState(false);
 const loadRoutes=()=>fetch(`${API}/api/routes`).then(r=>r.json()).then(setRoutes);
 const load=()=>Promise.all([fetch(`${API}/api/deliveries`).then(r=>r.json()),fetch(`${API}/api/routes`).then(r=>r.json()),fetch(`${API}/api/alerts`).then(r=>r.json())]).then(([d,r,a])=>{setItems(d);setRoutes(r);setAlerts(a)}).catch(()=>setError("API에 연결할 수 없습니다."));
 const loadWarehouse=()=>Promise.all([fetch(`${API}/api/warehouse/stock`).then(r=>r.json()),fetch(`${API}/api/warehouse/tasks`).then(r=>r.json()),fetch(`${API}/api/warehouse/ledger`).then(r=>r.json())]).then(([s,t,l])=>{setStocks(s);setTasks(t);setLedger(l)}).catch(()=>setError("창고 데이터에 연결할 수 없습니다."));
 const loadKpis=()=>fetch(`${API}/api/reports/daily-kpis?days=14`).then(r=>r.json()).then(setKpis).catch(()=>setError("KPI 보고서를 불러올 수 없습니다."));
 const loadOrders=()=>fetch(`${API}/api/orders`).then(r=>r.json()).then(setOrders).catch(()=>setError("주문 데이터를 불러올 수 없습니다."));
 const loadReplay=()=>Promise.all([fetch(`${API}/api/operations/dlq`).then(r=>r.json()),fetch(`${API}/api/operations/replay-audits`).then(r=>r.json())]).then(([events,audits])=>{setDeadLetters(events);setReplayAudits(audits);setError(current=>current==="복구 큐를 불러올 수 없습니다."?"":current)}).catch(()=>setError("복구 큐를 불러올 수 없습니다."));
 const loadPolicies=()=>Promise.all([fetch(`${API}/api/alert-policies`).then(r=>r.json()),fetch(`${API}/api/alert-policies/audits`).then(r=>r.json())]).then(([nextPolicies,nextAudits])=>{setPolicies(nextPolicies);setPolicyAudits(nextAudits)}).catch(()=>setError("경고 정책을 불러올 수 없습니다."));
 useEffect(()=>{load(); const source=new EventSource(`${API}/api/stream/deliveries`); source.onopen=()=>setConnected(true); source.onerror=()=>setConnected(false);
  source.addEventListener("delivery-update",e=>{const next=JSON.parse((e as MessageEvent).data);setItems(old=>[next,...old.filter(x=>x.id!==next.id)]);loadRoutes().catch(()=>{});loadOrders().catch(()=>{})});
  source.addEventListener("alert-update",e=>{const next:DeliveryAlert=JSON.parse((e as MessageEvent).data);setAlerts(old=>[next,...old.filter(x=>x.id!==next.id)])});return()=>source.close()},[]);
 const liveItems=useMemo(()=>items.filter(item=>item.status!=="DELIVERED"),[items]);
 const scopedItems=fleetScope==="LIVE"?liveItems:items;
 const visibleItems=useMemo(()=>{const query=fleetQuery.trim().toLowerCase();return query?scopedItems.filter(item=>[item.vehicleId,item.orderNumber,item.originName,item.destinationName].some(value=>value.toLowerCase().includes(query))):scopedItems},[scopedItems,fleetQuery]);
 useEffect(()=>{if(visibleItems.length&&!visibleItems.some(item=>item.id===selected))setSelected(visibleItems.find(item=>routes.some(route=>route.deliveryId===item.id))?.id||visibleItems[0].id)},[visibleItems,routes,selected]);
 function focusDelivery(id:string){if(items.find(item=>item.id===id)?.status==="DELIVERED")setFleetScope("ALL");setFleetQuery("");setSelected(id)}
 useEffect(()=>{loadWarehouse()},[]);
 useEffect(()=>{loadOrders();const timer=window.setInterval(loadOrders,15000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{loadKpis();const timer=window.setInterval(loadKpis,30000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{loadReplay();const timer=window.setInterval(loadReplay,15000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{loadPolicies();const timer=window.setInterval(loadPolicies,30000);return()=>window.clearInterval(timer)},[]);
 async function createOrder(e?:FormEvent){e?.preventDefault();setOrderBusy("create");setError("");try{const suffix=Date.now().toString().slice(-6);const response=await fetch(`${API}/api/orders`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({orderNumber:`ORD-${suffix}`,origin:{name:"Seoul Hub",lat:37.5665,lon:126.978},destination:{name:"Incheon DC",lat:37.4563,lon:126.7052}})});if(!response.ok)throw new Error();await loadOrders()}catch{setError("주문 생성에 실패했습니다.")}finally{setOrderBusy(undefined)}}
 async function dispatchOrder(id:string){setOrderBusy(id);setError("");try{const response=await fetch(`${API}/api/orders/${id}/dispatch`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({vehicleId:`TRUCK-${Math.ceil(Math.random()*9).toString().padStart(2,"0")}`})});if(!response.ok)throw new Error();const order:CustomerOrder=await response.json();if(order.deliveryId)setSelected(order.deliveryId);await Promise.all([loadOrders(),load()])}catch{setError("주문 배차에 실패했습니다.")}finally{setOrderBusy(undefined)}}
 async function receiveStock(){setWarehouseBusy(true);setError("");try{const suffix=Date.now().toString().slice(-6);const r=await fetch(`${API}/api/warehouse/receipts`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({referenceNumber:`ASN-${suffix}`,warehouseId:"SEOUL-HUB-A",sku:"COLD-BOX-01",quantity:10})});if(!r.ok)throw new Error();await loadWarehouse()}catch{setError("입고 처리에 실패했습니다.")}finally{setWarehouseBusy(false)}}
 async function pickAndDispatch(){setWarehouseBusy(true);setError("");try{const suffix=Date.now().toString().slice(-6);const pick=await fetch(`${API}/api/warehouse/outbounds`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({referenceNumber:`OUT-${suffix}`,warehouseId:"SEOUL-HUB-A",sku:"COLD-BOX-01",quantity:4})});if(!pick.ok)throw new Error();const task:WarehouseTask=await pick.json();const dispatched=await fetch(`${API}/api/warehouse/outbounds/${task.id}/dispatch`,{method:"POST"});if(!dispatched.ok)throw new Error();await loadWarehouse()}catch{setError("출고 처리에 실패했습니다. 먼저 재고를 입고해 주세요.")}finally{setWarehouseBusy(false)}}
 async function replay(id:string){setReplayBusy(id);setError("");try{const response=await fetch(`${API}/api/operations/dlq/${id}/replay`,{method:"POST",headers:{"X-Operator":"control-tower"}});if(!response.ok)throw new Error();await loadReplay()}catch{setError("DLQ 이벤트 재처리에 실패했습니다.")}finally{setReplayBusy(undefined)}}
 async function acknowledgeAlert(id:string){setAlertBusy(id);setError("");try{const response=await fetch(`${API}/api/alerts/${id}/acknowledgement`,{method:"POST",headers:{"X-Operator":"control-tower","X-Trace-Id":crypto.randomUUID()}});if(!response.ok)throw new Error();const next:DeliveryAlert=await response.json();setAlerts(old=>[next,...old.filter(alert=>alert.id!==next.id)])}catch{setError("경고 확인 처리에 실패했습니다.")}finally{setAlertBusy(undefined)}}
 async function savePolicy(policy:PolicyInput){setPolicyBusy(true);setError("");try{const response=await fetch(`${API}/api/alert-policies`,{method:"POST",headers:{"Content-Type":"application/json","X-Operator":"control-tower"},body:JSON.stringify(policy)});if(!response.ok)throw new Error();await loadPolicies()}catch{setError("경고 정책 저장에 실패했습니다. CLOSE < OPEN ≤ CRITICAL 순서를 확인해 주세요.")}finally{setPolicyBusy(false)}}
 async function resetPolicy(vehicleId:string){setPolicyBusy(true);setError("");try{const response=await fetch(`${API}/api/alert-policies/${encodeURIComponent(vehicleId)}`,{method:"DELETE",headers:{"X-Operator":"control-tower"}});if(!response.ok)throw new Error();await loadPolicies()}catch{setError("차량 정책을 전역 기본값으로 되돌리지 못했습니다.")}finally{setPolicyBusy(false)}}
 async function restorePolicy(auditId:string){setPolicyBusy(true);setError("");try{const response=await fetch(`${API}/api/alert-policies/audits/${auditId}/restore`,{method:"POST",headers:{"X-Operator":"control-tower"}});if(!response.ok)throw new Error();await loadPolicies()}catch{setError("감사 이력에서 경고 정책을 복원하지 못했습니다.")}finally{setPolicyBusy(false)}}
 const focus=items.find(x=>x.id===selected);
 const focusRoute=routes.find(x=>x.deliveryId===selected);
 const activeAlerts=alerts.filter(alert=>alert.status==="ACTIVE");
 return <main><header><div><p className="eyebrow">OPERATIONS / LIVE</p><h1>LogiTrack Control Tower</h1></div><div className={`signal ${connected?"on":""}`}><i/>{connected?"LIVE STREAM":"RECONNECTING"}</div></header>
  <section className="hero"><div><span>ACTIVE DELIVERIES</span><strong>{items.filter(x=>x.status!=="DELIVERED").length.toString().padStart(2,"0")}</strong></div><div><span>ACTIVE ALERTS</span><strong className={activeAlerts.length?"alertCount":""}>{activeAlerts.length.toString().padStart(2,"0")}</strong></div><div><span>FLEET PROGRESS</span><strong>{items.length?Math.round(items.reduce((n,x)=>n+x.progress,0)/items.length*100):0}%</strong></div><form onSubmit={createOrder}><button disabled={Boolean(orderBusy)}>+ CREATE ORDER</button></form></section>
  {error&&<p className="error">{error}</p>}
  <OrderFlowPanel orders={orders} busyId={orderBusy} onCreate={()=>createOrder()} onDispatch={dispatchOrder}/>
  <DailyKpiPanel rows={kpis} csvUrl={`${API}/api/reports/daily-kpis.csv?days=30`} pdfUrl={`${API}/api/reports/daily-kpis.pdf?days=30`}/>
  <section className="mapBoard"><div className="mapHeader"><div className="mapTitle"><p className="eyebrow">GEOSPATIAL OVERVIEW</p><h2>Live fleet map</h2><div className="mapControls"><div className="mapScope" aria-label="Fleet scope"><button type="button" aria-pressed={fleetScope==="LIVE"} className={fleetScope==="LIVE"?"active":""} onClick={()=>setFleetScope("LIVE")}>LIVE {liveItems.length}</button><button type="button" aria-pressed={fleetScope==="ALL"} className={fleetScope==="ALL"?"active":""} onClick={()=>setFleetScope("ALL")}>ALL {items.length}</button></div><label className="mapSearch" htmlFor="fleetSearch"><span>FIND</span><input id="fleetSearch" type="search" value={fleetQuery} onChange={event=>setFleetQuery(event.target.value)} placeholder="vehicle, order or place"/></label></div></div>{focus&&visibleItems.some(item=>item.id===focus.id)&&<div className="focusStats"><span><small>FOCUS</small>{focus.vehicleId}</span><span><small>PROGRESS</small>{Math.round(focus.progress*100)}%</span><span><small>ROUTE</small>{focusRoute?`${(focusRoute.distanceMeters/1000).toFixed(1)} km · ${focusRoute.provider.toUpperCase()}`:"CALCULATING"}</span><span><small>ETA</small>{focus.eta?new Date(focus.eta).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}):focus.status==="DELIVERED"?"ARRIVED":focusRoute?new Date(focusRoute.plannedEta).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}):"—"}</span></div>}</div>
   <FleetMap deliveries={visibleItems} routes={routes} selectedId={selected} onSelect={setSelected} emptyMessage={fleetQuery?`“${fleetQuery}” 검색 결과가 없습니다. 검색어를 지우거나 범위를 전환해 주세요.`:undefined}/></section>
  <AlertOperationsPanel alerts={alerts} deliveries={items} busyId={alertBusy} onSelect={focusDelivery} onAcknowledge={acknowledgeAlert}/>
  <AlertPolicyPanel policies={policies} audits={policyAudits} deliveries={items} busy={policyBusy} onSave={savePolicy} onReset={resetPolicy} onRestore={restorePolicy}/>
  <section className="board"><div className="boardTitle"><h2>Fleet telemetry</h2><span>{visibleItems.length} shown · {items.length} total · {fleetScope} scope</span></div>
  <div className="grid">{visibleItems.length===0?<div className="empty">{items.length===0?"배송을 생성하면 차량 위치 이벤트가 지도와 목록에 표시됩니다.":"현재 범위와 검색 조건에 맞는 배송이 없습니다."}</div>:visibleItems.map(d=>{const count=activeAlerts.filter(alert=>alert.deliveryId===d.id).length;return <article key={d.id} onClick={()=>focusDelivery(d.id)} className={selected===d.id?"selected":""}><div className="row"><span className={`badge ${d.status.toLowerCase()}`}>{d.status.replace("_"," ")}</span><b>{count>0&&<i className="cardAlert">{count}</i>}{d.vehicleId}</b></div><h3>{d.orderNumber}</h3><p>{d.originName} <em>→</em> {d.destinationName}</p><div className="track"><i style={{width:`${d.progress*100}%`}}/></div><div className="meta"><span>{Math.round(d.progress*100)}% complete</span><span>{d.currentLat?.toFixed(4)}, {d.currentLon?.toFixed(4)}</span></div></article>})}</div></section>
  <section className="warehouseBoard"><div className="warehouseHeader"><div><p className="eyebrow">WAREHOUSE / INVENTORY</p><h2>Stock control</h2></div><div className="warehouseActions"><button disabled={warehouseBusy} onClick={receiveStock}>+ RECEIVE 10</button><button disabled={warehouseBusy} onClick={pickAndDispatch}>PICK & DISPATCH 4</button></div></div>
   <div className="warehouseGrid"><div className="stockPane"><h4>AVAILABLE STOCK</h4>{stocks.length===0?<p className="warehouseEmpty">No inventory yet. Receive demo stock to begin.</p>:<div className="stockTable"><div className="stockRow head"><span>LOCATION / SKU</span><span>ON HAND</span><span>RESERVED</span><span>AVAILABLE</span></div>{stocks.slice(0,8).map(s=><div className="stockRow" key={s.id}><span><b>{s.warehouseId}</b><small>{s.sku}</small></span><strong>{s.onHand}</strong><strong>{s.reserved}</strong><strong className="available">{s.available}</strong></div>)}</div>}</div>
   <div className="ledgerPane"><h4>RECENT LEDGER</h4>{ledger.length===0?<p className="warehouseEmpty">Inventory movements will appear here.</p>:ledger.slice(0,7).map(e=><div className="ledgerRow" key={e.id}><span className={`movement ${e.transactionType.toLowerCase()}`}>{e.transactionType}</span><span><b>{e.sku}</b><small>{e.warehouseId}</small></span><span className="delta">{e.onHandDelta>0?`+${e.onHandDelta}`:e.onHandDelta||`R +${e.reservedDelta}`}</span></div>)}</div></div>
   <div className="taskStrip"><span>{tasks.filter(t=>t.status==="PICKED").length} awaiting dispatch</span><span>{tasks.filter(t=>t.status==="DISPATCHED").length} dispatched</span><span>{ledger.length} ledger movements loaded</span></div>
  </section>
  <ReplayOperationsPanel events={deadLetters} audits={replayAudits} busyId={replayBusy} onReplay={replay}/>
 </main>
}
