from pathlib import Path


source = Path("scripts/aws-runtime-audit.ps1").read_text(encoding="utf-8")
required = (
    "sts\", \"get-caller-identity",
    "Assert-RoleBoundary",
    "list-attached-role-policies",
    "get-role-policy",
    "must have exactly one trust statement",
    "OIDC condition set drifted",
    "ExpectedActionResources",
    "resource scope drifted",
    "inline policy contains an unexpected statement shape",
    "runtime backup bucket prefix condition drifted",
    "token.actions.githubusercontent.com:sub",
    "logitrack-staging-image-publisher",
    "describe-repositories",
    "ImageTagMutability",
    "ScanOnPush",
    "get-lifecycle-policy",
    "imageCountMoreThan",
    "disableApiTermination",
    "instanceInitiatedShutdownBehavior",
    "HttpTokens",
    "describe-instance-information",
    'PingStatus -eq "Online"',
    "LastPingDateTime",
    "AssociationStatus",
    "rootVolume.Encrypted",
    '($ports -join ",") -eq "80,443"',
    "Resolve-Ipv4WithRetry",
    "ec2:recover",
    "get-lifecycle-policy",
    "MaximumBackupAgeHours",
    "describe-snapshots",
    "schedule.CopyTags",
    'tags.SnapshotSchedule -eq "logitrack-staging-daily"',
    "duplicate source-volume key",
    "latest managed EBS snapshot is stale or future-dated",
    "get-public-access-block",
    "get-bucket-encryption",
    "get-bucket-lifecycle-configuration",
    "list-objects-v2",
    "head-object",
    '"--checksum-mode", "ENABLED"',
    "ChecksumSHA256",
    "latest PostgreSQL backup is stale or future-dated",
    "list-associations",
    "describe-association",
    "ApplyOnlyAtCronInterval",
    'backupTargets[0].Key -eq "InstanceIds"',
    'backupCommand.Contains("pg_restore --list")',
    'backupCommand.Contains("pg_restore --exit-on-error --no-owner --no-privileges")',
    'backupCommand.Contains("information_schema.tables")',
    'backupCommand.Contains("dropdb --if-exists --force")',
    'backupCommand.Contains("--sse AES256 --checksum-algorithm SHA256")',
    "describe-budget",
    "describe-notifications-for-budget",
)
missing = [control for control in required if control not in source]
if missing:
    raise SystemExit("ERROR: AWS runtime audit is missing controls: " + ", ".join(missing))
if any(token in source for token in ("remove-", "delete-", "terminate-", "put-", "update-", "create-")):
    raise SystemExit("ERROR: AWS runtime audit must remain read-only")
print("PASS: AWS runtime audit covers compute, network, recovery, backup, and budget boundaries")
