from pathlib import Path


audit_source = Path("scripts/github-cd-boundary-audit.ps1").read_text(encoding="utf-8")
pagination_source = Path("scripts/github-pagination.ps1").read_text(encoding="utf-8")
artifact_download_source = Path("scripts/github-artifact-download.ps1").read_text(encoding="utf-8")
source = audit_source + pagination_source + artifact_download_source
required = (
    "Invoke-RestMethod -Method Get",
    "$requestTimeoutSeconds = 30",
    "function Invoke-GitHubGetAll",
    '. (Join-Path $PSScriptRoot "github-pagination.ps1")',
    '. (Join-Path $PSScriptRoot "github-artifact-download.ps1")',
    '[ValidateRange(1, 100)][int]$MaximumPages = 100',
    '[System.Collections.Generic.HashSet[string]]',
    'function ConvertFrom-GitHubQueryString',
    'GitHub pagination repeated a page',
    'GitHub pagination contains ambiguous next links',
    'GitHub pagination changed the endpoint',
    'GitHub pagination changed a required query parameter',
    'GitHub pagination query is ambiguous',
    '[System.Text.Json.JsonDocument]::Parse',
    '[System.Text.Json.JsonValueKind]::Array',
    'GitHub pagination returned invalid JSON',
    'GitHub pagination response is not an array',
    'GitHub pagination response exceeded 100 items',
    '$document.Dispose()',
    '[ValidateRange(1, 120)][int]$TimeoutSeconds = 30',
    '-MaximumRedirection 0 -TimeoutSec $RequestTimeoutSeconds',
    '$response = & $RequestInvoker $uri $Headers $TimeoutSeconds',
    'rel="next"',
    'GitHub pagination escaped the repository',
    'GitHub pagination exceeded $MaximumPages pages',
    "/actions/permissions",
    "sha_pinning_required",
    "default_workflow_permissions",
    "/branches/main/protection",
    "allow_squash_merge",
    "delete_branch_on_merge",
    "secret_scanning.status",
    "secret_scanning_push_protection.status",
    "dependabot_security_updates.status",
    'Get-GitHubStatus "/vulnerability-alerts"',
    'Get-GitHubStatus "/automated-security-fixes"',
    'Invoke-GitHubGet "/private-vulnerability-reporting"',
    "privateVulnerabilityReporting.enabled",
    "/dependabot/alerts?state=open",
    'Invoke-GitHubGetAll -Path "/dependabot/alerts?state=open"',
    "/secret-scanning/alerts?state=open",
    'Invoke-GitHubGetAll -Path "/secret-scanning/alerts?state=open"',
    "/code-scanning/default-setup",
    'query_suite -eq "extended"',
    'schedule -eq "weekly"',
    "/code-scanning/alerts?state=open",
    'Invoke-GitHubGetAll -Path "/code-scanning/alerts?state=open"',
    "security_severity_level",
    "required_status_checks.strict",
    "Dependency vulnerability review",
    "required_pull_request_reviews",
    "required_approving_review_count",
    "dismiss_stale_reviews",
    "enforce_admins.enabled",
    "required_linear_history.enabled",
    "allow_force_pushes.enabled",
    "allow_deletions.enabled",
    "required_reviewers",
    "deployment-branch-policies",
    'name -eq "main"',
    "AWS_RUNTIME_ROLE_ARN",
    "ECR_REPOSITORY_PREFIX",
    "/environments/$Environment/secrets",
    "/actions/secrets",
    'expectedRepositorySecretNames = @("DOCKERHUB_TOKEN")',
    '"/actions/workflows/publish-dockerhub-images.yml"',
    '"/actions/workflows/dockerhub-provenance-audit.yml"',
    '"/actions/workflows/ci.yml/runs?branch=main&event=push&per_page=1"',
    'latestCiRun[0].status -eq "completed"',
    'latestCiRun[0].conclusion -eq "success"',
    '"/actions/workflows/dockerhub-provenance-audit.yml/runs?branch=main&per_page=1"',
    'auditRun.status -eq "completed"',
    'auditRun.conclusion -eq "success"',
    'auditAge.TotalHours -le 26',
    'mainCommittedAt = [DateTimeOffset]::Parse',
    '"/actions/runs/$($auditRun.id)/artifacts?per_page=10"',
    'expectedAuditArtifactName = "dockerhub-provenance-audit-$($mainCommit.sha)-$($auditRun.run_attempt)"',
    "auditArtifact.digest -match '^sha256:[0-9a-f]{64}$'",
    'auditArtifact.workflow_run.id -eq $auditRun.id',
    'artifactRetention.TotalDays -ge 29.9',
    'auditArtifact.archive_download_url -eq "$expectedArtifactUrl/zip"',
    'Save-GitHubArtifactArchive -ArchiveApiUri $auditArtifact.archive_download_url',
    'GitHub artifact endpoint did not return the expected redirect',
    'GitHub artifact redirect location is ambiguous',
    "'^productionresults[a-z0-9-]*\\.blob\\.core\\.windows\\.net$'",
    'GitHub artifact redirect target is not trusted',
    'function Assert-GitHubArtifactZipEntryType',
    'unixFileType -ne 0x8000',
    'unsafeDosAttributes -ne 0',
    'GitHub artifact ZIP entry is not a regular file',
    'unixMode -ne 0x81A4',
    'dosAttributes -ne 0x20',
    'GitHub artifact ZIP entry metadata is not canonical',
    'Assert-GitHubArtifactZipEntryType -Entry $entry',
    'auditArtifact.size_in_bytes -le 1MB',
    'downloadedArchiveSize -eq $auditArtifact.size_in_bytes',
    'downloadedArchiveDigest -eq $auditArtifact.digest',
    '[System.IO.Compression.ZipFile]::OpenRead($auditArchive)',
    'archiveEntries.Count -eq 11',
    'Select-Object -Unique).Count -eq 11',
    'entry.FullName -eq $entry.Name',
    'entry.Length -le 2MB',
    'entry.CompressedLength -le 1MB',
    'totalExpandedBytes -le 10MB',
    '$archive.Dispose()',
    'Expand-Archive -LiteralPath $auditArchive',
    'jsonFiles.Count -eq 10',
    'checksumLines.Count -eq 10',
    "Get-FileHash -LiteralPath $evidencePath -Algorithm SHA256",
    'tagEvidence.name -eq $mainCommit.sha',
    '$auditedDockerHubDigests[$service] = [string]$tagEvidence.digest',
    '@($tagEvidence.images).Count -eq 1',
    'verificationEvidence.Count -eq 1',
    'verifiedTimestamps.Count -eq 1',
    'verifiedTimestamps[0].type -eq "Tlog"',
    'verifiedTimestamps[0].uri -eq "https://rekor.sigstore.dev"',
    'transparencyTimestamp -ge $mainCommittedAt.AddMinutes(-5)',
    'transparencyTimestamp -le $auditCreatedAt.AddMinutes(5)',
    'statement.predicateType -eq "https://slsa.dev/provenance/v1"',
    'digest.sha256 -eq $expectedSubjectDigest',
    'certificate.subjectAlternativeName -eq $expectedSigner',
    'certificate.githubWorkflowName -eq "CI"',
    'certificate.githubWorkflowTrigger -eq "push"',
    'certificate.githubWorkflowSHA -eq $mainCommit.sha',
    'certificate.sourceRepositoryIdentifier -eq [string]$repositoryInfo.id',
    'certificate.sourceRepositoryOwnerIdentifier -eq [string]$repositoryInfo.owner.id',
    'certificate.buildConfigURI -eq $expectedBuildConfig',
    'certificate.runInvocationURI -eq $invocationId',
    'result.verifiedIdentity.runnerEnvironment -eq "github-hosted"',
    'buildDefinition.buildType -eq "https://actions.github.io/buildtypes/workflow/v1"',
    'dependencies[0].digest.gitCommit -eq $mainCommit.sha',
    'statement.predicate.runDetails.builder.id -eq $expectedSigner',
    'matchingStatements.Count -eq 1',
    'Remove-Item -LiteralPath $auditTempRoot -Recurse -Force',
    'https://hub.docker.com/v2/repositories/$Owner/logitrack-$service/',
    'https://hub.docker.com/v2/repositories/$Owner/logitrack-$service/tags/$($mainCommit.sha)',
    'dockerHubTag.digest -eq $auditedDockerHubDigests[$service]',
    '@($dockerHubTag.images).Count -eq 1',
    '$confirmedMainCommit = Invoke-GitHubGet "/commits/main"',
    'confirmedMainCommit.sha -eq $mainCommit.sha',
    'main changed while the boundary audit was running',
    "'^sha256:[0-9a-f]{64}$'",
    '$_ .os -eq "linux"'.replace("$_ ", "$_"),
    '$_.architecture -eq "amd64"',
)
missing = [control for control in required if control not in source]
if missing:
    raise SystemExit("ERROR: GitHub CD audit is missing controls: " + ", ".join(missing))
initial_main_index = audit_source.index('$mainCommit = Invoke-GitHubGet "/commits/main"')
docker_hub_index = audit_source.rindex("$dockerHubTag = Invoke-RestMethod")
confirmed_main_index = audit_source.index('$confirmedMainCommit = Invoke-GitHubGet "/commits/main"')
success_index = audit_source.index('Write-Output "PASS: GitHub main')
if not initial_main_index < docker_hub_index < confirmed_main_index < success_index:
    raise SystemExit("ERROR: GitHub CD audit must reconfirm main after Docker Hub verification and before reporting success")
authenticated_requests = [
    line
    for line in audit_source.splitlines()
    if ("Invoke-RestMethod" in line or "Invoke-WebRequest" in line) and "-Headers $headers" in line
]
if any("-TimeoutSec $requestTimeoutSeconds" not in line for line in authenticated_requests):
    raise SystemExit("ERROR: authenticated GitHub requests must have a bounded timeout")
if any("-MaximumRedirection 0" not in line for line in authenticated_requests):
    raise SystemExit("ERROR: authenticated GitHub API requests must reject redirects")
for hidden_result_filter in (
    "ci.yml/runs?branch=main&event=push&status=success",
    "dockerhub-provenance-audit.yml/runs?branch=main&status=success",
):
    if hidden_result_filter in audit_source:
        raise SystemExit("ERROR: GitHub CD audit must inspect the latest workflow result without hiding failures")
for mutation in ("-Method Post", "-Method Put", "-Method Patch", "-Method Delete"):
    if mutation in source:
        raise SystemExit(f"ERROR: GitHub CD audit must remain read-only: {mutation}")
print("PASS: GitHub audit covers PR protection, private reporting, dependency, secret, CodeQL, merge, deployment, action, and Docker Hub boundaries")
