from pathlib import Path


source = Path("scripts/github-cd-boundary-audit.ps1").read_text(encoding="utf-8")
required = (
    "Invoke-RestMethod -Method Get",
    "/actions/permissions",
    "sha_pinning_required",
    "default_workflow_permissions",
    "/branches/main/protection",
    "allow_squash_merge",
    "delete_branch_on_merge",
    "secret_scanning.status",
    "secret_scanning_push_protection.status",
    "dependabot_security_updates.status",
    'Get-GitHubStatus "/vulnerability-alerts"',
    'Get-GitHubStatus "/automated-security-fixes"',
    'Invoke-GitHubGet "/private-vulnerability-reporting"',
    "privateVulnerabilityReporting.enabled",
    "/dependabot/alerts?state=open",
    "/secret-scanning/alerts?state=open",
    "/code-scanning/default-setup",
    'query_suite -eq "extended"',
    'schedule -eq "weekly"',
    "/code-scanning/alerts?state=open",
    "security_severity_level",
    "required_status_checks.strict",
    "Dependency vulnerability review",
    "required_pull_request_reviews",
    "required_approving_review_count",
    "dismiss_stale_reviews",
    "enforce_admins.enabled",
    "required_linear_history.enabled",
    "allow_force_pushes.enabled",
    "allow_deletions.enabled",
    "required_reviewers",
    "deployment-branch-policies",
    'name -eq "main"',
    "AWS_RUNTIME_ROLE_ARN",
    "ECR_REPOSITORY_PREFIX",
    "/environments/$Environment/secrets",
    "/actions/secrets",
    'expectedRepositorySecretNames = @("DOCKERHUB_TOKEN")',
    '"/actions/workflows/publish-dockerhub-images.yml"',
    '"/actions/workflows/dockerhub-provenance-audit.yml"',
    '"/actions/workflows/ci.yml/runs?branch=main&event=push&status=success&per_page=1"',
    'latestCiRun[0].head_sha -eq $mainCommit.sha',
    '"/actions/workflows/dockerhub-provenance-audit.yml/runs?branch=main&status=success&per_page=1"',
    'auditRun.head_sha -eq $mainCommit.sha',
    'auditAge.TotalHours -le 26',
    '"/actions/runs/$($auditRun.id)/artifacts?per_page=10"',
    'expectedAuditArtifactName = "dockerhub-provenance-audit-$($mainCommit.sha)-$($auditRun.run_attempt)"',
    "auditArtifact.digest -match '^sha256:[0-9a-f]{64}$'",
    'auditArtifact.workflow_run.id -eq $auditRun.id',
    'artifactRetention.TotalDays -ge 29.9',
    'auditArtifact.archive_download_url -eq "$expectedArtifactUrl/zip"',
    'Invoke-WebRequest -Method Get -Uri $auditArtifact.archive_download_url',
    'auditArtifact.size_in_bytes -le 1MB',
    'downloadedArchiveSize -eq $auditArtifact.size_in_bytes',
    'downloadedArchiveDigest -eq $auditArtifact.digest',
    '[System.IO.Compression.ZipFile]::OpenRead($auditArchive)',
    'archiveEntries.Count -eq 11',
    'Select-Object -Unique).Count -eq 11',
    'entry.FullName -eq $entry.Name',
    'entry.Length -le 2MB',
    'entry.CompressedLength -le 1MB',
    'totalExpandedBytes -le 10MB',
    '$archive.Dispose()',
    'Expand-Archive -LiteralPath $auditArchive',
    'jsonFiles.Count -eq 10',
    'checksumLines.Count -eq 10',
    "Get-FileHash -LiteralPath $evidencePath -Algorithm SHA256",
    'tagEvidence.name -eq $mainCommit.sha',
    '$auditedDockerHubDigests[$service] = [string]$tagEvidence.digest',
    'statement.predicateType -eq "https://slsa.dev/provenance/v1"',
    'digest.sha256 -eq $expectedSubjectDigest',
    'certificate.subjectAlternativeName -eq $expectedSigner',
    'certificate.githubWorkflowSHA -eq $mainCommit.sha',
    'certificate.sourceRepositoryIdentifier -eq [string]$repositoryInfo.id',
    'certificate.sourceRepositoryOwnerIdentifier -eq [string]$repositoryInfo.owner.id',
    'certificate.buildConfigURI -eq $expectedBuildConfig',
    'certificate.runInvocationURI -eq $invocationId',
    'result.verifiedIdentity.runnerEnvironment -eq "github-hosted"',
    'buildDefinition.buildType -eq "https://actions.github.io/buildtypes/workflow/v1"',
    'dependencies[0].digest.gitCommit -eq $mainCommit.sha',
    'statement.predicate.runDetails.builder.id -eq $expectedSigner',
    'Remove-Item -LiteralPath $auditTempRoot -Recurse -Force',
    'https://hub.docker.com/v2/repositories/$Owner/logitrack-$service/',
    'https://hub.docker.com/v2/repositories/$Owner/logitrack-$service/tags/$($mainCommit.sha)',
    'dockerHubTag.digest -eq $auditedDockerHubDigests[$service]',
    "'^sha256:[0-9a-f]{64}$'",
    '$_ .os -eq "linux"'.replace("$_ ", "$_"),
    '$_.architecture -eq "amd64"',
)
missing = [control for control in required if control not in source]
if missing:
    raise SystemExit("ERROR: GitHub CD audit is missing controls: " + ", ".join(missing))
for mutation in ("-Method Post", "-Method Put", "-Method Patch", "-Method Delete"):
    if mutation in source:
        raise SystemExit(f"ERROR: GitHub CD audit must remain read-only: {mutation}")
print("PASS: GitHub audit covers PR protection, private reporting, dependency, secret, CodeQL, merge, deployment, action, and Docker Hub boundaries")
